### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by zyadamec** [ReadableLabs/readable-vscode#8]
**Describe the bug**
While commenting Python I get the error "Cannot read property 'split' of undefined"

**To Reproduce**
1. Highlight code below(Not sure why the code block isn't keeping the formatting.  Code format can bee seen here) https://imgur.com/a/tQGQOGv

`
def aws_heading_style():
    heading = NamedStyle(name="heading")
    #heading.font = Font(name='Segoe UI Light', size=11, bold=True)
    heading.number_format = '$#,##0.00'
    heading.fill = PatternFill(
        fill_type='solid',
        start_color='DDEBF7',
        end_color='DDEBF7')
    return heading
`

3. Click Ctrl + '
4. Error shows

**Expected behavior**
Comment generated

**Screenshots**
https://imgur.com/a/tQGQOGv

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version:
 https://imgur.com/a/tQGQOGv
 - Readable Version: 1.5.5

**Comment by victorchapman** [comment]
Issue has been fixed with an increase to the rate limit.
